Repository opengamedata/ogd-core, pull requests merged in 2024-11, with the labels that each got.

#234 New Lakeland features
  src/ogd/core/managers/ExportManager.py
  src/ogd/games/LAKELAND/LakelandLoader.py
  src/ogd/games/LAKELAND/features/CropBuildCount.py
  src/ogd/games/LAKELAND/features/DairyBuildCount.py
  src/ogd/games/LAKELAND/features/HouseBuildCount.py
  src/ogd/games/LAKELAND/features/HoversBeforeCropPlacement.py
  src/ogd/games/LAKELAND/features/TotalBuildCount.py
  src/ogd/games/LAKELAND/features/__init__.py
  src/ogd/games/LAKELAND/schemas/LAKELAND.json.template
Labels: Extractor

#237 Fix Shadowspect exports
  src/ogd/games/SHADOWSPECT/ShadowspectLoader.py
  src/ogd/games/SHADOWSPECT/features/SequenceWithinPuzzles.py
  src/ogd/games/SHADOWSPECT/schemas/SHADOWSPECT.json.template
Labels: bug

#239 Bring CustomDetector.py.template up-to-date.
  src/ogd/core/generators/detectors/CustomDetector.py.template
Labels: documentation
