Repository opengamedata/ogd-core, pull requests merged in 2024-06, with the labels that each got.

#155 Add basic base class for testing configs.
  src/ogd/core/schemas/configs/TestConfigSchema.py
Labels: testing

#144 Bloom Feature review
  src/ogd/core/managers/ExportManager.py
  src/ogd/games/BLOOM/BloomLoader.py
  src/ogd/games/BLOOM/__init__.py
  src/ogd/games/BLOOM/detectors/__init__.py
  src/ogd/games/BLOOM/features/ActiveTime.py
  src/ogd/games/BLOOM/features/AverageActiveTime.py
  src/ogd/games/BLOOM/features/CountyUnlockCount.py
  src/ogd/games/BLOOM/features/FailCount.py
  src/ogd/games/BLOOM/features/NumberOfSessionsPerPlayer.py
  src/ogd/games/BLOOM/features/PersistedThroughFailure.py
  src/ogd/games/BLOOM/features/__init__.py
  src/ogd/games/BLOOM/schemas/BLOOM.json.template
Labels: new feature, Extractor

#157 Fixes for Bloom Features
  src/ogd/games/BLOOM/BloomLoader.py
  src/ogd/games/BLOOM/features/ActiveTime.py
  src/ogd/games/BLOOM/features/CountyUnlockCount.py
  src/ogd/games/BLOOM/features/FailCount.py
  src/ogd/games/BLOOM/features/__init__.py
Labels: bug

#170 Add support for universal/builtin features
  src/ogd/core/generators/GeneratorLoader.py
  src/ogd/core/generators/extractors/CustomPercountFeature.py.template
  src/ogd/core/generators/extractors/__init__.py
  src/ogd/core/generators/extractors/builtin/BuiltinExtractor.py
  src/ogd/core/generators/extractors/builtin/CountEvent.py
  src/ogd/core/generators/extractors/builtin/Timespan.py
  src/ogd/core/generators/extractors/builtin/__init__.py
  src/ogd/core/managers/EventManager.py
  src/ogd/core/managers/ExportManager.py
  src/ogd/core/managers/FeatureManager.py
  src/ogd/core/processors/DetectorProcessor.py
  src/ogd/core/processors/ExtractorProcessor.py
  src/ogd/core/processors/GeneratorProcessor.py
  src/ogd/core/processors/PlayerProcessor.py
  src/ogd/core/processors/PopulationProcessor.py
  src/ogd/core/processors/SessionProcessor.py
  src/ogd/core/registries/DetectorRegistry.py
  src/ogd/core/registries/ExtractorRegistry.py
  src/ogd/core/registries/GeneratorRegistry.py
  src/ogd/core/registries/__init__.py
  src/ogd/games/AQUALAB/AqualabLoader.py
  src/ogd/games/CRYSTAL/CrystalLoader.py
  src/ogd/games/ICECUBE/IcecubeLoader.py
  src/ogd/games/JOURNALISM/JournalismLoader.py
  src/ogd/games/JOWILDER/JowilderLoader.py
  src/ogd/games/LAKELAND/LakelandLoader.py
  src/ogd/games/MAGNET/MagnetLoader.py
  src/ogd/games/PENGUINS/PenguinsLoader.py
  src/ogd/games/SHADOWSPECT/ShadowspectLoader.py
  src/ogd/games/SHIPWRECKS/ShipwrecksLoader.py
  src/ogd/games/THERMOVR/ThermoVRLoader.py
  src/ogd/games/THERMOVR/schemas/THERMOVR.json.template
  src/ogd/games/WAVES/WaveLoader.py
  src/ogd/games/WAVES/features/SessionSucceedCount.py
  src/ogd/games/WAVES/features/__init__.py
  src/ogd/games/WAVES/schemas/WAVES.json.template
Labels: new feature
